# Generated by Django 5.2 on 2026-03-22 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "short_description",
                    models.TextField(verbose_name="Краткое содержание"),
                ),
                ("full_content", models.TextField(verbose_name="Полное содержание")),
                (
                    "posted",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(2026, 3, 23, 1, 4, 54, 399322),
                        verbose_name="Опубликована",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog_images/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("review", "Обзор"),
                            ("news", "Новости"),
                            ("guide", "Гайд"),
                            ("compare", "Сравнение"),
                            ("tips", "Советы"),
                        ],
                        default="review",
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        unique=True,
                        verbose_name="URL-метка",
                    ),
                ),
            ],
        ),
    ]
