# Generated by Django 5.2.11 on 2026-03-23 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blog_author_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Статьи блога'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 3, 23, 11, 30, 28, 902979), verbose_name='Опубликована'),
        ),
        migrations.AlterModelTable(
            name='blog',
            table='blog_posts',
        ),
    ]
