# Generated by Django 5.2 on 2026-04-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_blog_posted_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="image_url",
        ),
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog_images/",
                verbose_name="Изображение статьи",
            ),
        ),
    ]
