# Generated by Django 5.2 on 2026-04-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_category_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                verbose_name="Изображение товара",
            ),
        ),
    ]
